layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  show_language: true
  show_stargazers_count: false
  show_forks_count: false
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    forks: true
    projects:
    # - repo-name

nav_links:
  - name: ABOUT
    link: /about
  - name: RESUME
    link: /resume.pdf
  - name: BLOG
    link: /blog

social_media:
  github: menushka
  facebook: menushka.weeratunga
  twitter: aggromoose
  linkedin: menushkaweeratunga
  # behance: your_username
  # dribbble: your_username
  # stackoverflow: your_user_id
  # youtube: your_username

topics:
  - name: TypeScript
    description: TypeScript is a superset of JavaScript that compiles to clean JavaScript output.
    web_url: https://github.com/topics/typescript
    image_url: http://localhost:4000/assets/img/typescript.png
  - name: Node.js
    description: Node.js is a tool for executing JavaScript in a variety of environments.
    web_url: https://github.com/topics/nodejs
    image_url: http://localhost:4000/assets/img/nodejs.png
  - name: Machine Learning
    description: Machine learning is the practice of teaching a computer to learn.
    web_url: https://github.com/topics/machine-learning
    image_url: http://localhost:4000/assets/img/machine-learning.png
  - name: Virtual Reality
    description: Virtual reality is a fully immersive and interactive computer-simulated environment.
    web_url: https://github.com/topics/virtual-reality
    image_url: http://localhost:4000/assets/img/virtual-reality.png
